### ISSUE TITLE
Realtime Database Sample

### ISSUE THREAD

**Issue by formatCvt** [FirebaseExtended/cocos2dx-cpp-sample#2]
Do you have any plans about Realtime Database sample?

**Comment by alexames** [comment]
I do! Database and Storage will have sample projects made available shortly. 

In the mean time you can also look at the [Firebase C++ QuickStart Samples](https://github.com/firebase/quickstart-cpp/tree/master/database/testapp) to get an idea of how to use the library.

**Comment by formatCvt** [comment]
ok, thanks!

**Comment by alexames** [comment]
Just checked in a Firebase Realtime Database sample app. A Firebase Storage sample is on the way too.
