### ISSUE TITLE
Unable to find Method com/google/firebase/remoteconfig/FirebaseRemoteConfig.setDefaults. Please verify the AAR which contains the com/google/firebase/remoteconfig/FirebaseRemoteConfig class is included in your app.

### ISSUE THREAD

**Issue by NanZii** [FirebaseExtended/cocos2dx-cpp-sample#20]
When i run sample code remote_config in cocos2dx-cpp-sample repository, i caught "A/firebase: Unable to find Method com/google/firebase/remoteconfig/FirebaseRemoteConfig.setDefaults (signature '(ILjava/lang/String;)V', instance). Please verify the AAR which contains the com/google/firebase/remoteconfig/FirebaseRemoteConfig class is included in your app." error.
Anyone have idea to fix that ? Tks

**Comment by formatCvt** [comment]
this samples are outdated and uses old way to include firebase dependencies for android. Try new way: https://firebase.google.com/docs/cpp/setup?platform=android#add_sdk

**Comment by NanZii** [comment]
I tried with new way but still this bug occur.
- System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/google/firebase/remoteconfig/FirebaseRemoteConfig;.setDefaults(ILjava/lang/String;)V

- A/firebase: Unable to find Method com/google/firebase/remoteconfig/FirebaseRemoteConfig.setDefaults (signature '(ILjava/lang/String;)V', instance).  Please verify the AAR which contains the com/google/firebase/remoteconfig/FirebaseRemoteConfig class is included in your app.

Seem this bug just happen with remoteconfig. I tested with Firebase Analytics, it's ok

**Comment by NanZii** [comment]
I upgraded to firebase_cpp_sdk_6.0.0 this bug is resolved, maybe i am used old sdk
