### ISSUE TITLE
incompatiblity with android sdk and cpp sdk

### ISSUE THREAD

**Issue by dudochkin-victor** [FirebaseExtended/cocos2dx-cpp-sample#7]
There some incompatibility:
- firebasee android sdk - 10.2.4
- firebase cpp sdk - 3.1.1
So Firebase send invite but cant decode project id anr return Error 500.

05-12 04:21:18.676 16100-16156/ru.gogoo.sushi D/cocos2d-x debug info: Initializing Firebase for Android.
05-12 04:21:18.706 16100-16100/ru.gogoo.sushi D/Cocos2dxActivity: onWindowFocusChanged() hasFocus=true
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/google/firebase/FirebaseOptions$Builder;.setProjectId(Ljava/lang/String;)Lcom/google/firebase/FirebaseOptions$Builder;"
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at org.cocos2dx.lib.Cocos2dxRenderer.nativeInit(Native Method)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at org.cocos2dx.lib.Cocos2dxRenderer.onSurfaceCreated(Cocos2dxRenderer.java:72)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/google/firebase/FirebaseOptions;.getProjectId()Ljava/lang/String;"
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at org.cocos2dx.lib.Cocos2dxRenderer.nativeInit(Native Method)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at org.cocos2dx.lib.Cocos2dxRenderer.onSurfaceCreated(Cocos2dxRenderer.java:72)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
05-12 04:21:18.766 16100-16115/ru.gogoo.sushi W/art: Suspending all threads took: 21.118ms
05-12 04:21:18.776 16100-16144/ru.gogoo.sushi D/FA: Connected to remote service

**Comment by formatCvt** [comment]
hi, 3.1.2 just released, try it please

**Comment by stewartmiles** [comment]
@dudochkin-victor this warning (it was just a warning) was fixed with the release of the 4.0.0 Android SDK.  We've also just released the 4.0.0 C++ SDK with a number of bug fixes https://firebase.google.com/support/release-notes/cpp-relnotes#4.0.0

Cheers,
Stewart
