### ISSUE TITLE
Error to complie in IOS 

### ISSUE THREAD

**Issue by saulex** [FirebaseExtended/cocos2dx-cpp-sample#9]
Hi, in android work perfect compiled and run, (release and debug), If compiled with Xcode and command line "cocos compile" I got the same error result:
ld: warning: object file (/Users/<user>/Documents/<root-pryect>/cocos2dx-cpp-sample/sample_project/bin/debug/ios/libcocos2d iOS.a(ftlzw.ios8_i386.o)) was built for newer iOS version (7.0) than being linked (6.0)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_FIRTransactionResult", referenced from:
      objc-class-ref in firebase_database(database_reference_ios_3449459c15aef7e31c8afe79eaa7793d.o)
  "_OBJC_CLASS_$_FIRDatabase", referenced from:
      objc-class-ref in firebase_database(database_ios_a510d85c52f977653ce87c71622b82b9.o)
  "_OBJC_CLASS_$_FIRPhoneAuthProvider", referenced from:
      objc-class-ref in firebase_auth(credential_ios_8842bea456a3d08991633ce351da4833.o)
  "_OBJC_CLASS_$_FIRGoogleAuthProvider", referenced from:
      objc-class-ref in firebase_auth(credential_ios_8842bea456a3d08991633ce351da4833.o)
  "_OBJC_CLASS_$_FIRDatabaseReference", referenced from:
      objc-class-ref in firebase_database(database_reference_ios_3449459c15aef7e31c8afe79eaa7793d.o)
  "_OBJC_CLASS_$_FIRGitHubAuthProvider", referenced from:
      objc-class-ref in firebase_auth(credential_ios_8842bea456a3d08991633ce351da4833.o)
  "_OBJC_CLASS_$_FIREmailAuthProvider", referenced from:
      objc-class-ref in firebase_auth(credential_ios_8842bea456a3d08991633ce351da4833.o)
  "_OBJC_CLASS_$_FIRAuth", referenced from:
      objc-class-ref in firebase_auth(auth_ios_aeeb64b45d2cf07d8a483d9b8a93eadf.o)
  "_OBJC_CLASS_$_FIRTwitterAuthProvider", referenced from:
      objc-class-ref in firebase_auth(credential_ios_8842bea456a3d08991633ce351da4833.o)
  "_OBJC_CLASS_$_FIRPhoneAuthCredential", referenced from:
      objc-class-ref in firebase_auth(user_ios_8c8add148e36bde3d728607314e5511d.o)
  "_OBJC_CLASS_$_FIROAuthProvider", referenced from:
      objc-class-ref in firebase_auth(credential_ios_8842bea456a3d08991633ce351da4833.o)
  "_OBJC_CLASS_$_FIROptions", referenced from:
      objc-class-ref in firebase(app_ios_bf85e0fc73a1028793d185e5f1e44a98.o)
  "_OBJC_CLASS_$_FIRFacebookAuthProvider", referenced from:
      objc-class-ref in firebase_auth(credential_ios_8842bea456a3d08991633ce351da4833.o)
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in firebase(app_ios_bf85e0fc73a1028793d185e5f1e44a98.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld /Users/<user>/Documents/<root-pryect>/cocos2d-x-3.13.1/cocos2dxnew-cpp-sample/cocos2dx-cpp-sample/sample_project/bin/debug/ios/HelloCpp-mobile.app/HelloCpp-mobile normal i386
(1 failure)
Build failed: Take a look at the output above for details.

I don't know I need to fixer.

Thank you.

Mac OSX Capitan v10.11.6
Xcode Version 8.2.1 (8C1002)

**Comment by alexames** [comment]
Can you explain in a little bit more detail the steps you took to build the project? You shouldn't need to run `cocos compile` when doing an iOS build. Did you follow the steps on [this page](https://github.com/firebase/cocos2dx-cpp-sample#ios)? Make sure your Cocoapods are up to date too (`pod update`). Also make sure you're running the `.xcworkspace` file and not the `.xcodeproj` file, if you weren't already.

**Comment by saulex** [comment]
Sorry, I don't know IOS plataform, I install "pod" and all work perfect.
